### ISSUE TITLE
app crashes immediately when building master

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#18]
Setup:
* Android Studio 3.6.3
* Samsung SM G800F (galaxy S5 mini)

When I run the app it builds fine, installs on the device, launches it
... and crashes immediately without any logs in studio 
"Polkawallet has stopped" on the device screen

Tried on AVD Pixel 2 Oreo as well. same story
(but I had to "import" the project instead of "open" because the Android Studio Menu "Tools" didn't show the AVD Manager, nor SDK Manager. Seems to be [this issue](https://github.com/flutter/flutter-intellij/issues/2159). However, importing makes a big mess with project structure.

console shows:
```
Launching lib\main.dart on SM G800F in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
```

**Comment by brenzi** [comment]
...when "importing" the project, I had a logcat window (which didn't appear with "open")

```
2020-05-09 19:57:46.790 5393-5393/io.polkawallet.www.polka_wallet I/zygote: Not late-enabling -Xcheck:jni (already on)
2020-05-09 19:57:47.688 5393-5393/io.polkawallet.www.polka_wallet W/zygote: Unexpected CPU variant for X86 using defaults: x86
2020-05-09 19:57:48.593 5393-5393/io.polkawallet.www.polka_wallet D/AndroidRuntime: Shutting down VM
2020-05-09 19:57:48.603 5393-5393/io.polkawallet.www.polka_wallet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.polkawallet.www.polka_wallet, PID: 5393
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.polkawallet.www.polka_wallet/io.polkawallet.www.polkawalletflutter.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "io.polkawallet.www.polkawalletflutter.MainActivity" on path: DexPathList[[zip file "/data/app/io.polkawallet.www.polka_wallet-HXeQsRhT7vmv4V0f283OJQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.polkawallet.www.polka_wallet-HXeQsRhT7vmv4V0f283OJQ==/lib/x86, /data/app/io.polkawallet.www.polka_wallet-HXeQsRhT7vmv4V0f283OJQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.polkawallet.www.polkawalletflutter.MainActivity" on path: DexPathList[[zip file "/data/app/io.polkawallet.www.polka_wallet-HXeQsRhT7vmv4V0f283OJQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.polkawallet.www.polka_wallet-HXeQsRhT7vmv4V0f283OJQ==/lib/x86, /data/app/io.polkawallet.www.polka_wallet-HXeQsRhT7vmv4V0f283OJQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2020-05-09 19:57:48.671 5393-5445/io.polkawallet.www.polka_wallet I/ResourceExtractor: Found extracted resources res_timestamp-2-1589046102354
2020-05-09 19:57:48.671 5393-5445/io.polkawallet.www.polka_wallet I/ResourceExtractor: Resource version mismatch res_timestamp-2-1589047065488
2020-05-09 19:57:53.474 5393-5445/io.polkawallet.www.polka_wallet I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
2020-05-09 19:57:53.475 5393-5445/io.polkawallet.www.polka_wallet I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
2020-05-09 19:57:53.625 5393-5445/io.polkawallet.www.polka_wallet I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
```

**Comment by brenzi** [comment]
flutter version:
```
C:\flutter\bin\flutter.bat --no-color upgrade
Flutter is already up to date on channel stable
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (7 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
Process finished with exit code 0
```

**Comment by brenzi** [comment]
Is there a way to cleanly upgrade the project for the given Android Studio and flutter version?

**Comment by RomeroYang** [comment]
Try branch develop

**Comment by brenzi** [comment]
worked
