### ISSUE TITLE
won't connect to Kusama network

### ISSUE THREAD

**Issue by brenzi** [polkawallet-io/polkawallet-flutter#41]
After starting the app and creating a new account, the assets screen tells me "connecting remote node...."

The log hints at a bug:
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
Hot reload received invalid response: {type: Sentinel, kind: Collected, valueAsString: <collected>}
D/EGL_emulation( 6053): eglCreateContext: 0xa9d34680: maj 3 min 0 rcv 3
D/        ( 6053): HostConnection::get() New Host Connection established 0xa21a3800, tid 6413
D/EGL_emulation( 6053): eglMakeCurrent: 0xa9d34680: ver 3 0 (tinfo 0xa2183560)
D/        ( 6053): HostConnection::get() New Host Connection established 0xa21a35c0, tid 6412
D/EGL_emulation( 6053): eglCreateContext: 0xa2185060: maj 3 min 0 rcv 3
D/EGL_emulation( 6053): eglMakeCurrent: 0xa2185060: ver 3 0 (tinfo 0xa2183520)
I/Choreographer( 6053): Skipped 366 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 6053): eglMakeCurrent: 0xa9d333c0: ver 3 0 (tinfo 0xa9d1b330)
D/EGL_emulation( 6053): eglMakeCurrent: 0xa2185060: ver 3 0 (tinfo 0xa2183520)
I/flutter ( 6053): notification_plugin initialised: true
I/flutter ( 6053): initailizing app state
I/flutter ( 6053): sys locale: en
I/flutter ( 6053): No observables detected in the build method of Observer
I/flutter ( 6053): #3      _WalletAppState.build.<anonymous closure> (package:polka_wallet/app.dart:176:38)
I/flutter ( 6053): webview loaded for network kusama
I/flutter ( 6053): js file loaded
E/flutter ( 6053): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'home' was called on null.
E/flutter ( 6053): Receiver: null
E/flutter ( 6053): Tried calling: home
E/flutter ( 6053): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 6053): #1      UI.checkUpdate (package:polka_wallet/utils/UI.dart:80:38)
E/flutter ( 6053): #2      _WalletAppState._checkUpdate (package:polka_wallet/app.dart:118:8)
E/flutter ( 6053): <asynchronous suspension>
E/flutter ( 6053): #3      _WalletAppState._initStore (package:polka_wallet/app.dart:135:7)
E/flutter ( 6053): #4      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 6053): #5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 6053): #6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 6053): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 6053): #8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 6053): #9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 6053): #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter ( 6053): #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter ( 6053): #12     AsyncAction.run (package:mobx/src/api/async/async_action.dart)
E/flutter ( 6053): #13     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 6053): #14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 6053): #15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 6053): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 6053): #17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 6053): #18     Future._complete (dart:async/future_impl.dart:516:7)
E/flutter ( 6053): #19     new Future.microtask.<anonymous closure> (dart:async/future.dart:202:16)
E/flutter ( 6053): #20     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 6053): #21     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6053): #22     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6053): #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 6053): #24     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 6053): #25     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6053): #26     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6053): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 6053): #28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6053): #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6053): 
I/flutter ( 6053): received msg: {"path":"log","data":"main js loaded"}
I/flutter ( 6053): received msg: {"path":"uid=0;account.initKeys","data":{"0":{"0xbe9db4ecc6821c60f81a38c50526c971a94901368555b64e091da9bca8e7cc7f":"15JvwuyGi3jchh1W3n7d9asgFRuk11c8sb6uH5MPSN9G4tsM"},"2":{"0xbe9db4ecc6821c60f81a38c50526c971a94901368555b64e091da9bca8e7cc7f":"GtFTu45UdV51opRrqsfuPQXYQCL7NsBFUDAWSdzN5LEdWwF"},"42":{"0xbe9db4ecc6821c60f81a38c50526c971a94901368555b64e091da9bca8e7cc7f":"5GNdoaiCrGU9G9zz694d1S3XPov6Ji3zo6NR7nN2tH7jtK7Z"}}}
I/chromium( 6053): [INFO:CONSOLE(1)] "Uncaught TypeError: settings.connectAll is not a function", source:  (1)
I/flutter ( 6053): received msg: {"path":"uid=2;account.genPubKeyIcons","data":[["0xbe9db4ecc6821c60f81a38c50526c971a94901368555b64e091da9bca8e7cc7f","<svg viewBox='0 0 64 64' xmlns='http://www.w3.org/2000/svg'><circle cx='32' cy='32' fill='#eee' r='32' /><circle cx='32' cy='8' fill='hsl(174, 87%, 15%)' r='5' /><circle cx='32' cy='20' fill='hsl(247, 87%, 15%)' r='5' /><circle cx='21.607695154586736' cy='14' fill='hsl(219, 87%, 15%)' r='5' /><circle cx='11.215390309173472' cy='20' fill='hsl(286, 87%, 53%)' r='5' /><circle cx='21.607695154586736' cy='26' fill='hsl(101, 87%, 75%)' r='5' /><circle cx='11.215390309173472' cy='32' fill='hsl(219, 87%, 15%)' r='5' /><circle cx='11.215390309173472' cy='44' fill='hsl(174, 87%, 15%)' r='5' /><circle cx='21.607695154586736' cy='38' fill='hsl(247, 87%, 15%)' r='5' /><circle cx='21.607695154586736' cy='50' fill='hsl(219, 87%, 15%)' r='5' /><circle cx='32' cy='56' fill='hsl(286, 87%, 53%)' r='5' /><circle cx='32' cy='44' fill='hsl(101, 87%, 75%)' r='5' /><circle cx='42.392304845413264' cy='5
```

**Comment by brenzi** [comment]
actually, this issue only applies to [my fork](https://github.com/encointer/polkawallet-flutter/tree/encointer) will close this and need to see what I broke downstream
